// src/utils/quarto.ts
import fs from 'fs';
import path from 'path';
import YAML from 'yaml';
import { withBase } from './base';

export interface QuartoNavLink {
  text: string;
  href: string;
  children?: { text: string; href: string }[];
}

export interface QuartoConfig {
  title: string;
  description: string;
  navLinks: QuartoNavLink[];
  ctaLink: { text: string; href: string };
}

export interface QuartoPageData {
  title: string;
  subtitle: string;
  description: string;
  htmlContent: string;
}

/**
 * Loads and parses _quarto.yml to ensure navigation and metadata follow Quarto.
 */
export function getQuartoConfig(): QuartoConfig {
  const ymlPath = path.resolve(process.cwd(), '_quarto.yml');
  const fileContent = fs.readFileSync(ymlPath, 'utf8');
  const parsed = YAML.parse(fileContent);

  const rawLeft = parsed?.website?.navbar?.left || [];
  const rawRight = parsed?.website?.navbar?.right || [];

  const navLinks: QuartoNavLink[] = rawLeft.map((item: any) => ({
    text: item.text,
    href: item.href,
    children: item.menu ? item.menu.map((m: any) => ({ text: m.text, href: m.href })) : undefined,
  }));

  const ctaItem = rawRight[0] || {
    text: '¡Inscríbete!',
    href: 'https://docs.google.com/forms/d/e/1FAIpQLSc7rDxBwNfyn-kl7dL-n6cunoIeHJ2K8BwpLvJGb4jq_6uL0Q/viewform',
  };

  return {
    title: parsed?.website?.title || 'ISLP Bolivia',
    description: parsed?.website?.description || 'Competencia Boliviana de Pósters Estadísticos',
    navLinks,
    ctaLink: { text: ctaItem.text, href: ctaItem.href },
  };
}

/**
 * Normalizes HTML generated by Quarto:
 * - Rewrites relative links to assets/img
 * - Rewrites internal page links (../../blog, ../../recursos, etc.)
 * - Rewrites root-relative URLs with Astro BASE_URL
 * - Rewrites islpOpenLightbox calls
 */
export function cleanQuartoHtml(rawHtml: string): string {
  let html = rawHtml.replace(/<header id="title-block-header"[\s\S]*?<\/header>/i, '');

  // 1. Rewrite relative links to root (../../, ../, etc.)
  html = html.replace(/href=["'](?:\.\.\/)+(?:index\.html)?["']/g, () => {
    return `href="${withBase('/')}"`;
  });
  html = html.replace(/href=["'](?:\.\.\/)+(#[^"']*)["']/g, (_m, hash) => {
    return `href="${withBase('/' + hash)}"`;
  });

  // 2. Rewrite relative links to main sections (recursos, blog, contacto)
  html = html.replace(/href=["'](?:\.\.\/)+(recursos|blog|contacto)(?:\.html)?(#[^"']*)?["']/g, (_m, page, hash) => {
    return `href="${withBase(`/${page}${hash || ''}`)}"`;
  });

  // 3. Rewrite links to posts (e.g. ../posts/..., ../../posts/..., ../content/posts/..., posts/...)
  html = html.replace(/href=["'](?:(?:\.\.\/)+(?:content\/)?)?posts\/([^"']+?)(?:\.html)?(#[^"']*)?["']/g, (_m, slug, hash) => {
    return `href="${withBase(`/posts/${slug}${hash || ''}`)}"`;
  });

  // 3b. Rewrite root-relative links (e.g. /#galeria, /recursos#checklist, /blog#..., /posts/...)
  html = html.replace(/href=["']\/(#[^"']*)["']/g, (_m, hash) => {
    return `href="${withBase('/' + hash)}"`;
  });
  html = html.replace(/href=["']\/(recursos|blog|contacto)(?:\.html)?(#[^"']*)?["']/g, (_m, page, hash) => {
    return `href="${withBase(`/${page}${hash || ''}`)}"`;
  });
  html = html.replace(/href=["']\/posts\/([^"']+?)(?:\.html)?(#[^"']*)?["']/g, (_m, slug, hash) => {
    return `href="${withBase(`/posts/${slug}${hash || ''}`)}"`;
  });

  // 4. Rewrite relative or root links to assets or images (e.g. ../../img/..., img/..., /img/...)
  html = html.replace(/(href|src)=["'](?:(?:\.\.\/)+|\/)?(assets|img)\/([^"']+)["']/g, (_m, attr, dir, file) => {
    return `${attr}="${withBase(`/${dir}/${file}`)}"`;
  });

  // 5. Rewrite islpOpenLightbox calls
  html = html.replace(/islpOpenLightbox\(["'](?:(?:\.\.\/)+|\/)?(img|assets)\/([^"']+)["']/g, (_m, dir, file) => {
    return `islpOpenLightbox("${withBase(`/${dir}/${file}`)}"`;
  });

  return html;
}

/**
 * Extracts the rendered HTML content generated by Quarto for a specific page slug.
 */
export function getQuartoPage(slug: string): QuartoPageData {
  const filePath = path.resolve(process.cwd(), `.quarto-build/content/${slug}.html`);
  
  if (!fs.existsSync(filePath)) {
    throw new Error(`Quarto build file not found for slug "${slug}" at ${filePath}. Run "quarto render" first.`);
  }

  const fullHtml = fs.readFileSync(filePath, 'utf8');

  // Extract <main id="quarto-document-content">...</main>
  const mainMatch = fullHtml.match(/<main[^>]*id="quarto-document-content"[^>]*>([\s\S]*?)<\/main>/i);
  let htmlContent = mainMatch ? mainMatch[1] : fullHtml;

  // Extract title
  const titleMatch = fullHtml.match(/<h1 class="title">([\s\S]*?)<\/h1>/i) || fullHtml.match(/<title>([\s\S]*?)<\/title>/i);
  const title = titleMatch ? titleMatch[1].replace(/–.*$/, '').replace(/<[^>]*>/g, '').trim() : 'ISLP Bolivia';

  // Extract subtitle
  const subtitleMatch = fullHtml.match(/<p class="subtitle[^"]*">([\s\S]*?)<\/p>/i);
  const subtitle = subtitleMatch ? subtitleMatch[1].replace(/<[^>]*>/g, '').trim() : '';

  // Extract description
  const descMatch = fullHtml.match(/<div class="description">([\s\S]*?)<\/div>/i) || fullHtml.match(/<meta name="description" content="([^"]*)"/i);
  const description = descMatch ? descMatch[1].replace(/<[^>]*>/g, '').trim() : '';

  // Clean and normalize HTML content
  htmlContent = cleanQuartoHtml(htmlContent);

  return {
    title,
    subtitle,
    description,
    htmlContent,
  };
}
